import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Provider from '@/redux/CustomProvider'
const vazirmtn = localFont({
  src: "../public/fonts/Vazirmatn-Light.ttf",
});

export const metadata: Metadata = {
  title: "Nafisa Gold",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#000000",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body
        className={`${vazirmtn.className}`}
      >
        <Provider >
        {children}
        </Provider>
      </body>
    </html>
  );
}
